# -*- coding: utf-8 -*-
"""Copy of DataSci Bootcamp - Rock Paper Scissor - Python.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/16iUf0kYHK9w7m-T8ylPVFDRrRa6GB953

### Rock-Paper-Scissor game

**Game Logics**
- rock crushes scissors
- paper covers rock
- scissors cuts paper
"""

import random

#RPS Logic

supported_action = ("rock","paper","scissors")

results = [
          ["win",0],
          ["lose",0],
          ["draw",0]
          ]

while True:
    user_action = input("Your Action (rock, paper, scissors or quit) <- ").lower()
    random_action = random.sample(supported_action,1)
    random_value = random_action[0]

    if user_action in supported_action or user_action == "quit":
        if user_action == "quit":
            print("Goodbye XD")
            print("""
            RESULT SUMMARY""")
            for result in results:
                print(f""" 
                {result[0]} : {result[1]}
                  """)
            print("####################")
            break
        elif random_value == user_action:
            print(f"Com Action: {random_value}")
            print(f"Your Action: {user_action}")
            print("Result: Tie")
            results[2][1] = results[2][1] + 1
        elif (random_value == "rock" and user_action == "scissors") or (random_value == "paper" and user_action == "rock") or  (random_value == "scissors" and user_action == "paper"):
            print(f"Com Action: {random_value}")
            print(f"Your Action: {user_action}")
            print("Result: Lose")
            results[1][1] = results[1][1] + 1
        else:
            print(f"Com Action: {random_value}")
            print(f"Your Action: {user_action}")
            print("Result: Win")
            results[0][1] = results[0][1] + 1

        for result in results:
            print(f"""
            {result[0]} : {result[1]}
            """)
        print("####################")

    else:
        print("Incorrect action. Please try again.")

