# -*- coding: utf-8 -*-
"""Pyrhon Exercise.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1PLX0RusAIfjXKFJyc19Oqq-L81XW_Fus

#(Q1) เขียนโปรแกรมเพื่อรับ input เป็น string และแสดงผลเป็น string นั้นในลำดับที่กลับกัน
"""

# Take input as string
string = input("Enter a string: ")

# Reverse the string
reverse_string = string[::-1]

# Output the reversed string
print("Reversed string:", reverse_string)

#Enter a string: hello
#Reversed string: olleh

"""#(Q2) เขียนโปรแกรมเพื่อคำนวณลำดับฟิโบนัคชี (Fibonacci) โดยรับ input เป็นจำนวนของลำดับและแสดงผลตามจำนวนนั้น (เริ่มนับจาก 0) """

# for loop

# Ask user for input
n = int(input("Enter the number of the Fibonacci sequence: "))

# Initialize variables
fibonacci_seq = [0, 1]

# Calculate the sequence
for i in range(2, n):
    next_num = fibonacci_seq[i-1] + fibonacci_seq[i-2]
    fibonacci_seq.append(next_num)

# Display the sequence
print("Fibonacci sequence:")
for num in fibonacci_seq:
    print(num, end=" ")

#recursive function

def fibonacci(n):
    if n == 0:
        return 0
    elif n == 1:
        return 1
    else:
        return fibonacci(n-1) + fibonacci(n-2)

# Ask user for input
n = int(input("Enter the number of the Fibonacci sequence: "))

# Calculate and display the sequence
print("Fibonacci sequence:")
for i in range(n):
    print(fibonacci(i), end=" ")

fibonacci(8)

"""# (Q3) เขียนโปรแกรมเพื่อแสดงรูปแบบตามที่กำหนด โดยรับ input เป็นขนาดของ pattern เป็นจำนวนคี่ และแสดงผลเป็น pattern ที่สัมพันธ์กับขนาดที่ได้รับ """

n = int(input("Enter an odd number: "))

# check if n is odd
if n % 2 == 0:
    print("Please enter an odd number.")
else:
    # loop through the rows
    for i in range(n):
        # loop through the columns
        for j in range(n):
            # check if i and j are equal or if their sum is n-1
            if i == j or i + j == n - 1:
                print("*", end="")
            else:
                print("-", end="")
        # print a newline character at the end of each row
        print()

"""#(Q4) เขียนโปรแกรมเพื่อแสดงผลตัวอักษร A และ B โดยรับ input เป็นจำนวนของตัวอักษร A และ B จากนั้นแสดงผลตัวอักษรทั้งสองตามจำนวนที่ได้รับ โดย ห้ามไม่ให้มีการแสดงผลตัวอักษรเดียวกันซ้ำติดกันเกิน 2 ครั้ง และจะต้องใช้ตัวอักษรทั้งหมดให้ครบตามจำนวน """

num_a = int(input("Enter the number of A characters: "))
num_b = int(input("Enter the number of B characters: "))

# initialize variables to keep track of the number of consecutive characters
consecutive_a = 0
consecutive_b = 0

# loop through each character in the output
for i in range(num_a + num_b):
    # check if we should output an A or a B
    if num_a > num_b:
        # output an A if we have more As than Bs
        if consecutive_a < 2:
            print("A", end="")
            consecutive_a += 1
            consecutive_b = 0
            num_a -= 1
        else:
            print("B", end="")
            consecutive_a = 0
            consecutive_b += 1
            num_b -= 1
    else:
        # output a B if we have more Bs than As
        if consecutive_b < 2:
            print("B", end="")
            consecutive_b += 1
            consecutive_a = 0
            num_b -= 1
        else:
            print("A", end="")
            consecutive_b = 0
            consecutive_a += 1
            num_a -= 1

# print a newline character at the end of the output
print()